// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohrgnjkgmishrbbrzkdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ocmduamtnbWlzaHJiYnJ6a2RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NTA2OTYsImV4cCI6MjA2NDAyNjY5Nn0.PxPOsMMNpHyZIjVo5w0-3_Mqn6IP8bRWyJaxywhPcoQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);